name: Tag new version
description: Add new version tag for the current branch.

inputs: {} # No inputs required

outputs:
  branch:
    description: The name of the current branch that has been tagged.
  version:
    description: The new version tag created.
  prev-version:
    description: The previous version tag before the new one was created.

runs:
  using: ubuntu_latest
  steps:

    - name: Get new version
      id: get_version
      uses: xaxay/action_library/actions/get-version@master

    - name: Tag new version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         # Retrieve the branch and versions from outputs of get-version action
        BRANCH=${{ steps.get_version.outputs.branch }}
        VERSION=${{ steps.get_version.outputs.version }}
        NEW_VERSION=${{ steps.get_version.outputs.next-version }}

        # Add new version tag and push
        git tag -a "$NEW_VERSION" -m "Version $NEW_VERSION"
        git push origin "$NEW_VERSION"

        # Set the outputs
        echo "::set-output name=branch::$BRANCH"
        echo "::set-output name=version::$NEW_VERSION"
        echo "::set-output name=prev-version::$VERSION"
