name: Get version
description: Get current and next versions for a specified branch name.

inputs:
  branch:
    description: The name of the branch for which version information should be retrieved.

outputs:
  branch:
    description: The name of the branch for which version information was retrieved.
  version:
    description: The current latest version tag.
  next-version:
    description: The next version tag.

runs:
  # using: ubuntu_latest
  steps:
    # - env:
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      BRANCH=${{ inputs.branch }}

      # Fallback to current branch name if input branch is not provided
      if [[ -z "$BRANCH" ]]; then
        BRANCH="${GITHUB_REF#refs/heads/}"
      fi
      
      echo "Getting version information for branch $BRANCH"

      TAGS=$(git tag --list --merged $BRANCH)
      VERSION_TAGS=$(echo "$TAGS" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$')
      
      VERSION=$(echo "$VERSION_TAGS" | sort -V | tail -n1)

      if [ -z "$VERSION" ]; then
        echo "Error: No version tags found"
        exit 1
      fi
      echo "Latest tag version is $VERSION"

      MAJOR=$(echo "$VERSION" | cut -d. -f1)
      MINOR=$(echo "$VERSION" | cut -d. -f2)
      PATCH=$(echo "$VERSION" | cut -d. -f3)

      NEW_PATCH=$((PATCH + 1))
      NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
      echo "New tag version is $NEW_VERSION"

      echo "::set-output name=branch::$BRANCH"
      echo "::set-output name=next-version::$NEW_VERSION"
      echo "::set-output name=version::$VERSION"
