name: Get version
description: Get current and next versions for a specified branch name.

inputs:
  branch:
    description: The name of the branch for which version information should be retrieved.
    required: true
    defuault: ""
  version_prefix:
    description:
    required: true
    default: ""

outputs:
  branch:
    description: The name of the branch for which version information was retrieved.
  version:
    description: The current latest version tag.
  next_version:
    description: The next version tag.

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "Getting branch version information ... GITHUB_REF=${GITHUB_REF}"
