name: Test Custom Actions

on: [push,workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print tags
        run: echo $(git tag -l "3.1.*" --merged ${{ github.ref }})

      - name: Use Custom Action from Action Library
        uses: xaxay/action_library/.github/actions/get-version@master

