name: Test Custom Actions

on: [push,workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

    # - name: Use Custom Action from Action Library
    #   uses: xaxay/action_library/.github/actions/tag-new-version@master
    #   with:
    #     some-input: value
    #   # env:
    #     # GITHUB_TOKEN: ${{ secrets.REPO_SECRET }}
